'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'EN' | 'FR' | 'AR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    pricing: 'Pricing',
    docs: 'Docs',
    contact: 'Contact',
    login: 'Log In',
    signup: 'Sign Up',
    heroTitle: 'Deploy [Recommendation Instances] for Every Store and Channel',
    heroSubtitle: 'Kliki gives teams a clear SaaS workflow for deploying engines, streaming events, and serving personalized recommendations from one platform.',
    startBuilding: 'Create Your First Instance',
    readDocs: 'Read the Docs',
    prototype: 'Built for recommendation teams',
    whyChoose: 'Why Teams Use Kliki',
    whyDesc: 'Kliki replaces scattered scripts and ad hoc dashboards with one recommendation control plane.',
    classicalAI: 'Traditional Setup',
    kliki: 'Kliki',
    goRecommend: 'Kliki',
    instantLearning: 'Learns from live traffic immediately',
    realTime: 'Updates with every event and refresh',
    lowCompute: 'Simple setup with minimal overhead',
    contextAware: 'Adapts to each customer and catalog',
    rees46Title: 'Live workspace status',
    rees46Desc: 'Each instance shows a real endpoint, current status, and a workspace-specific API key so teams can ship safely.',
    rees46Source: 'Workspace metadata',
    builtFor: 'Built for recommendation operations',
    builtForDesc: 'Kliki keeps catalog, event, and recommendation flows visible so teams can deploy and monitor with confidence.',
    ecommerce: 'Retail personalization',
    ecommerceDesc: 'Show related products at the moment a shopper is deciding what to add next.',
    media: 'Content discovery',
    mediaDesc: 'Use recent activity to surface the next article, video, or collection that fits the session.',
    research: 'Marketplace ranking',
    researchDesc: 'Bring long-tail items into the recommendation flow instead of letting them disappear in the catalog.',
    footerTagline: 'Recommendation infrastructure for stores, marketplaces, and content platforms.',
    readyToRev: 'Ready to launch recommendations?',
    scaleIntel: 'Create a workspace, connect events, and start serving recommendations.',
    getStartedFree: 'Create an account',
    contactSales: 'Contact sales',
    integrations: 'Platform',
    builtInConnectors: 'Connect your stack',
    builtInDesc: 'Use the dashboard to provision a workspace, copy the API key, and connect your storefront or backend.',
    pricingHero: 'Simple pricing for [active recommendation workloads].',
    pricingSubtitle: 'Choose a tier that matches your traffic, data volume, and support needs.',
    pricingBadge: 'Pay-As-You-Go',
    pricingUnit: '/ 1k interactions',
    pricingCommitment: 'No hidden fees.',
    pricingCTA: 'Start with Bronze',
    pricingFeature1: 'Instance-based pricing for each workspace',
    pricingFeature2: 'Recommendation and event endpoints included',
    pricingFeature3: 'Live dashboard for status and usage',
    pricingFeature4: 'API keys and workspace isolation',
    pricingFeature5: 'Algerian Dinar billing',
    pricingEnterprise: 'Need a custom volume plan?',
    pricingEnterpriseLink: 'Talk to sales',
    pricingValueTitle1: 'Deploy quickly.',
    pricingValueDesc1: 'Create a workspace and connect an instance in minutes.',
    pricingValueTitle2: 'Track usage clearly.',
    pricingValueDesc2: 'See the cost and activity of each deployment.',
    pricingValueTitle3: 'Support for Arabic teams.',
    pricingValueDesc3: 'Use the platform in the language your team prefers.',
    docsNavGettingStarted: 'Getting started',
    docsNavIntro: 'Introduction',
    docsNavHow: 'How it works',
    docsNavQuickstart: 'Quickstart',
    docsNavIntegration: 'Integration',
    docsNavShopify: 'Instance setup',
    docsNavWoo: 'Event ingestion',
    docsNavApi: 'REST API',
    docsNavConcepts: 'Core concepts',
    docsNavInstances: 'Workspaces',
    docsNavInteractions: 'Events',
    docsNavPrefs: 'Recommendation flow',
    docsTitle: 'Kliki documentation',
    docsIntro: 'Kliki helps teams create isolated recommendation instances, send interaction events, and request personalized results from one platform.',
    docsHowTitle: 'How it works',
    docsHowSubtitle: 'Workspace, event, and recommendation flow',
    docsHowBody: 'Each workspace owns a unique API key and a dedicated instance. You send events into that instance, then request recommendations back from the same tenant.',
    docsHowBullet1: 'Every workspace is isolated.',
    docsHowBullet2: 'Events and recommendations use the same instance id.',
    docsHowBullet3: 'Dashboard pages show live status and endpoints.',
    docsQuickstartTitle: 'Quickstart',
    docsQuickstartBody: 'Provision a workspace, create an instance, and start sending events in three steps.',
    docsIntCard1Title: 'Create a workspace',
    docsIntCard1Desc: 'Register the account that owns your recommendation data.',
    docsIntCard2Title: 'Create an instance',
    docsIntCard2Desc: 'Assign a tier, platform, and API key to one deployment.',
    docsIntCard3Title: 'Send events',
    docsIntCard3Desc: 'Track views, clicks, and purchases through the API.',
    docsShopifyTitle: 'Instance setup',
    docsShopifyBody: 'Each instance receives its own API key, endpoint URL, and live status view inside the dashboard.',
    docsApiTitle: 'REST API reference',
    docsApiBody: 'Use the REST API to create instances, inject events, and fetch recommendations for a user or session.',
    docsInstancesTitle: 'Workspaces',
    docsInstancesBody: 'A workspace is the isolated runtime for a single recommendation deployment. Each instance has its own key, status, and event stream.'
  },
  FR: {
    pricing: 'Tarifs',
    docs: 'Docs',
    contact: 'Contact',
    login: 'Connexion',
    signup: 'Commencer',
    heroTitle: 'Transformez Vos Visiteurs en Acheteurs grâce aux [Recommandations Intelligentes]',
    heroSubtitle: 'Kliki affiche automatiquement à chaque client les produits qu\'il est le plus susceptible d\'acheter — pour booster vos ventes sans effort supplémentaire de votre part.',
    startBuilding: 'Vendre Plus Intelligemment',
    readDocs: 'Voir Comment Ça Marche',
    prototype: 'Conçu pour les équipes recommandation',
    whyChoose: 'Pourquoi les Boutiques Choisissent Kliki',
    whyDesc: 'Les anciens outils devinent. Kliki sait. Voilà la différence pour votre boutique.',
    classicalAI: 'Outils Traditionnels',
    kliki: 'Kliki',
    goRecommend: 'Kliki',
    instantLearning: 'Apprend instantanément ce que veulent vos clients',
    realTime: 'Se met à jour en temps réel à chaque visite',
    lowCompute: 'Aucun coût de configuration — prêt à l\'emploi',
    contextAware: 'S\'adapte à chaque client, à chaque visite',
    rees46Title: 'Statut du workspace en direct',
    rees46Desc: 'Chaque instance affiche un endpoint réel, un statut actuel et une clé API dédiée.',
    rees46Source: 'Métadonnées du workspace',
    builtFor: 'Plus de Ventes. Moins d\'Effort.',
    builtForDesc: 'Kliki travaille en silence — en affichant le bon produit, au bon client, au bon moment.',
    ecommerce: 'Augmentez le Panier Moyen',
    ecommerceDesc: 'Quand un client consulte un produit, Kliki suggère immédiatement ce que des clients similaires ont acheté. Plus de pertinence = plus d\'articles.',
    media: 'Faites Revenir Vos Clients',
    mediaDesc: 'Kliki retient ce que chaque client a consulté et acheté — sa prochaine visite se sentira personnalisée, pas aléatoire.',
    research: 'Vendez Tout Votre Catalogue',
    researchDesc: 'Arrêtez de perdre des ventes sur des produits oubliés. Kliki met en avant des articles de toute votre boutique selon ce qu\'ont aimé des clients similaires.',
    footerTagline: 'L\'outil de recommandation intelligent pour les boutiques algériennes en ligne.',
    readyToRev: 'Prêt à Vendre Plus ?',
    scaleIntel: 'Rejoignez les boutiques algériennes qui grandissent déjà avec Kliki.',
    getStartedFree: 'Essayer Kliki Gratuitement',
    contactSales: 'Nous Parler',
    integrations: 'Compatible avec Votre Boutique',
    builtInConnectors: 'Branchez et C\'est Parti',
    builtInDesc: 'Utilisez le dashboard pour provisionner un workspace, copier la clé API et connecter votre storefront ou backend.',
    pricingHero: 'Commencez [Gratuitement]. Payez en grandissant.',
    pricingSubtitle: 'Facturation simple à l\'usage — vous ne payez que ce que vous utilisez.',
    pricingBadge: 'Paiement à l\'Usage',
    pricingUnit: '/ 1k interactions',
    pricingCommitment: 'Sans abonnement. Sans frais initiaux.',
    pricingCTA: 'Commencer Gratuitement',
    pricingFeature1: '5 000 premières interactions gratuites chaque mois',
    pricingFeature2: 'Produits & recommandations illimités',
    pricingFeature3: 'Mise à jour en temps réel à chaque visite',
    pricingFeature4: 'Tableau de bord & analyse des ventes',
    pricingFeature5: 'Paiement local (Dinar Algérien)',
    pricingEnterprise: 'Besoin d\'un plan personnalisé ?',
    pricingEnterpriseLink: 'Contacter les Ventes',
    pricingValueTitle1: 'Prêt en Minutes.',
    pricingValueDesc1: 'Connectez votre boutique et voyez les résultats rapidement.',
    pricingValueTitle2: 'Suivez Votre Usage.',
    pricingValueDesc2: 'Voyez exactement combien de recommandations vous servez.',
    pricingValueTitle3: 'Fonctionne en Arabe.',
    pricingValueDesc3: 'Entièrement localisé pour les acheteurs et boutiques algériens.',
    docsNavGettingStarted: 'Démarrage',
    docsNavIntro: 'Introduction',
    docsNavHow: 'Comment ça Marche',
    docsNavQuickstart: 'Démarrage Rapide',
    docsNavIntegration: 'Intégration',
    docsNavShopify: 'Extension Shopify',
    docsNavWoo: 'Ingestion d\'événements',
    docsNavApi: 'API REST',
    docsNavConcepts: 'Concepts Clés',
    docsNavInstances: 'Instances',
    docsNavInteractions: 'Interactions',
    docsNavPrefs: 'Comment Fonctionnent les Recommandations',
    docsTitle: 'Documentation Kliki',
    docsIntro: 'Kliki affiche automatiquement à chaque client de votre boutique les produits qu\'il est le plus susceptible d\'acheter — en temps réel, sans aucun travail manuel de votre part.',
    docsHowTitle: 'Comment Ça Marche',
    docsHowSubtitle: 'Correspondance Intelligente en Coulisses',
    docsHowBody: 'À chaque visite d\'un client, Kliki observe discrètement ce qu\'il parcourt et achète. Il compare ensuite son comportement à celui d\'autres clients pour trouver des tendances — et suggère le bon produit au bon moment.',
    docsHowBullet1: 'Pas de règles manuelles à configurer.',
    docsHowBullet2: 'S\'améliore automatiquement à chaque visite.',
    docsHowBullet3: 'Fonctionne dès le premier client.',
    docsQuickstartTitle: 'Démarrage Rapide',
    docsQuickstartBody: 'Connectez Kliki à votre boutique en minutes via l\'une de ces trois méthodes :',
    docsIntCard1Title: 'Extension Shopify',
    docsIntCard1Desc: 'Installation en un clic depuis l\'App Store Shopify. Sans code.',
    docsIntCard2Title: 'Créer une instance',
    docsIntCard2Desc: 'Attribuez un plan, une plateforme et une clé API à un déploiement.',
    docsIntCard3Title: 'API REST',
    docsIntCard3Desc: 'Pour les boutiques personnalisées — connectez-vous via notre API simple.',
    docsShopifyTitle: 'Extension Shopify',
    docsShopifyBody: 'Installez l\'extension Kliki directement depuis l\'App Store Shopify. Elle ajoute automatiquement des recommandations sur vos pages produits, votre panier et votre page d\'accueil.',
    docsApiTitle: 'Référence API REST',
    docsApiBody: 'Pour les boutiques avec des configurations personnalisées, utilisez notre API REST pour suivre les interactions et récupérer les recommandations.',
    docsInstancesTitle: 'Instances',
    docsInstancesBody: 'Une Instance est l\'environnement de recommandation dédié à votre boutique. Chaque boutique connectée obtient sa propre instance avec une clé API unique et ses propres données.'
  },
  AR: {
    pricing: 'الأسعار',
    docs: 'الدليل',
    contact: 'تواصل معنا',
    login: 'تسجيل الدخول',
    signup: 'ابدأ الآن',
    heroTitle: 'حوّل زوار متجرك إلى [مشترين فعليين]',
    heroSubtitle: 'كليكي يعرض لكل زبون المنتجات اللي يحتمل يشتريها — تبيع أكثر بدون ما تبذل مجهود إضافي.',
    startBuilding: 'ابدأ تبيع أذكى',
    readDocs: 'شوف كيفاش يخدم',
    prototype: 'مصمم لفرق التوصيات',
    whyChoose: 'علاش أصحاب المتاجر يختارون كليكي',
    whyDesc: 'الأدوات القديمة تخمّن. كليكي يعرف. هذا هو الفرق لمتجرك.',
    classicalAI: 'الأدوات التقليدية',
    kliki: 'كليكي',
    goRecommend: 'كليكي',
    instantLearning: 'يفهم ما يريده زبائنك من أول زيارة',
    realTime: 'يتحدّث مع كل زيارة جديدة',
    lowCompute: 'بدون إعداد — يشتغل مباشرة',
    contextAware: 'يتكيّف مع كل زبون في كل مرة',
    rees46Title: 'حالة الـ workspace مباشرة',
    rees46Desc: 'كل instance يظهر endpoint حقيقي، وحالة محدثة، ومفتاح API مخصص.',
    rees46Source: 'بيانات الـ workspace',
    builtFor: 'مبيعات أكثر. مجهود أقل.',
    builtForDesc: 'كليكي يشتغل في الخلفية — يعرض المنتج الصح للزبون الصح في اللحظة الصح.',
    ecommerce: 'زيد قيمة كل طلبية',
    ecommerceDesc: 'كي زبون يشوف منتج، كليكي يقترح له على طول ما اشتراه زبائن مشابهين. اقتراحات أدق = سلة أكبر.',
    media: 'خلي زبائنك يرجعو',
    mediaDesc: 'كليكي يتذكر ما تصفحه كل زبون واشتراه — في الزيارة الجاية يشوف المنتجات اللي تهمو حقًا.',
    research: 'بيع من كامل كتالوجك',
    researchDesc: 'وقف تخسر مبيعات على منتجات منسية. كليكي يبرز منتجات من كل ركن في متجرك بناءً على ما أحبه زبائن مشابهين.',
    footerTagline: 'أداة التوصيات الذكية للمتاجر الإلكترونية الجزائرية.',
    readyToRev: 'مستعد تبيع أكثر؟',
    scaleIntel: 'انضم لأصحاب المتاجر الجزائرية اللي كبرو مع كليكي.',
    getStartedFree: 'جرب كليكي مجانًا',
    contactSales: 'تواصل معنا',
    integrations: 'يتوافق مع متجرك',
    builtInConnectors: 'وصّل وابدأ',
    builtInDesc: 'استعمل dashboard لإنشاء workspace، نسخ مفتاح API، وربط storefront أو backend.',
    pricingHero: 'ابدأ [مجانًا]. ادفع كي تكبر.',
    pricingSubtitle: 'تسعير بسيط — تدفع بس على ما تستخدمه.',
    pricingBadge: 'ادفع حسب الاستخدام',
    pricingUnit: '/ 1k تفاعل',
    pricingCommitment: 'بدون اشتراك. بدون دفع مسبق.',
    pricingCTA: 'ابدأ مجانًا',
    pricingFeature1: 'أول 5,000 تفاعل مجانًا كل شهر',
    pricingFeature2: 'منتجات وتوصيات بلا حدود',
    pricingFeature3: 'تحديث فوري مع كل زيارة',
    pricingFeature4: 'لوحة تحكم وتحليل المبيعات',
    pricingFeature5: 'دعم الدفع بالدينار الجزائري',
    pricingEnterprise: 'تحتاج خطة مخصصة؟',
    pricingEnterpriseLink: 'تواصل مع المبيعات',
    pricingValueTitle1: 'جاهز في دقائق.',
    pricingValueDesc1: 'وصّل متجرك وشوف النتائج بسرعة.',
    pricingValueTitle2: 'تابع استخدامك.',
    pricingValueDesc2: 'شوف بالضبط قداش توصيات تقدم.',
    pricingValueTitle3: 'يشتغل بالعربية.',
    pricingValueDesc3: 'مُهيَّأ بالكامل للمتاجر والمشترين الجزائريين.',
    docsNavGettingStarted: 'البداية',
    docsNavIntro: 'مقدمة',
    docsNavHow: 'كيفاش يشتغل',
    docsNavQuickstart: 'بداية سريعة',
    docsNavIntegration: 'التوصيل',
    docsNavShopify: 'إضافة Shopify',
    docsNavWoo: 'استقبال الأحداث',
    docsNavApi: 'الـ API',
    docsNavConcepts: 'المفاهيم الأساسية',
    docsNavInstances: 'المتاجر المربوطة',
    docsNavInteractions: 'التفاعلات',
    docsNavPrefs: 'كيفاش تشتغل التوصيات',
    docsTitle: 'دليل كليكي',
    docsIntro: 'كليكي يعرض لكل زبون في متجرك المنتجات اللي يحتمل يشتريها — في الوقت الحقيقي، بدون ما تدير شي من عندك.',
    docsHowTitle: 'كيفاش يشتغل',
    docsHowSubtitle: 'ذكاء يشتغل في الخلفية',
    docsHowBody: 'كي زبون يزور متجرك، كليكي يراقب بهدوء ما يتصفحه وما يشتريه. يحلل سلوكه ويقارنه بزبائن مشابهين — ومن هنا يقدر يقترح المنتج الصح في اللحظة الصح.',
    docsHowBullet1: 'بدون قواعد يدوية تحتاج تحددها.',
    docsHowBullet2: 'يتحسن تلقائيًا مع كل زيارة.',
    docsHowBullet3: 'يشتغل من أول زبون.',
    docsQuickstartTitle: 'بداية سريعة',
    docsQuickstartBody: 'توصّل بمتجرك في دقائق باستخدام إحدى الطرق التالية:',
    docsIntCard1Title: 'إضافة Shopify',
    docsIntCard1Desc: 'نصيبها بنقرة واحدة من متجر تطبيقات Shopify. بدون كود.',
    docsIntCard2Title: 'إنشاء instance',
    docsIntCard2Desc: 'حدد الخطة والمنصة ومفتاح API لنشر واحد.',
    docsIntCard3Title: 'الـ API',
    docsIntCard3Desc: 'للمتاجر المخصصة — وصّل عبر الـ API البسيط تاعنا.',
    docsShopifyTitle: 'إضافة Shopify',
    docsShopifyBody: 'نصّب إضافة كليكي مباشرة من متجر تطبيقات Shopify. بعد التنصيب، تضيف توصيات تلقائيًا على صفحات المنتجات، السلة، والصفحة الرئيسية.',
    docsApiTitle: 'مرجع الـ API',
    docsApiBody: 'للمتاجر ذات الإعدادات المخصصة، استخدم الـ API تاعنا لتتبع التفاعلات واسترجاع التوصيات.',
    docsInstancesTitle: 'المتاجر المربوطة',
    docsInstancesBody: 'كل متجر تربطه بكليكي يحصل على بيئة توصيات خاصة به — بمفتاح API فريد وبياناته الخاصة.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('EN');

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['EN']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'AR' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
