'use client';

import React, { createContext, useContext, useEffect, useState, ReactNode } from 'react';

type Language = 'EN' | 'FR' | 'AR';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  EN: {
    // ---- Navigation / common ----
    pricing: 'Pricing',
    docs: 'Guide',
    contact: 'Contact',
    login: 'Log In',
    signup: 'Start Free',
    dashboard: 'Dashboard',

    // ---- Hero ----
    prototype: 'Smart recommendations for Algerian stores',
    heroTitle: 'Turn Your Visitors Into [Real Buyers]',
    heroSubtitle: "Kliki shows every shopper the products they're most likely to buy — so you sell more without any extra work.",
    startBuilding: 'Start Selling Smarter',
    readDocs: 'See How It Works',

    // ---- Comparison ----
    whyChoose: 'Why Stores Choose Kliki',
    whyDesc: "Old tools guess. Kliki knows. That's the difference for your store.",
    classicalAI: 'Traditional Tools',
    kliki: 'Kliki',
    goRecommend: 'Kliki',
    trad1: 'Shows the same products to every customer',
    trad2: 'Needs weeks of setup and data collection',
    trad3: 'Expensive to maintain and update',
    trad4: 'Gets it wrong for new customers',
    instantLearning: 'Learns what your customers want instantly',
    realTime: 'Updates in real time with every visit',
    lowCompute: 'No setup cost — ready to use',
    contextAware: 'Adapts to each customer, every visit',

    // ---- Segments / benefits ----
    builtFor: 'More Sales. Less Effort.',
    builtForDesc: 'Kliki works quietly in the background — showing the right product, to the right customer, at the right moment.',
    ecommerce: 'Grow Every Order',
    ecommerceDesc: 'When a customer views a product, Kliki instantly suggests what similar shoppers bought. More relevance means bigger carts.',
    media: 'Bring Customers Back',
    mediaDesc: 'Kliki remembers what each customer viewed and bought — so their next visit feels personal, not random.',
    research: 'Sell Your Whole Catalog',
    researchDesc: 'Stop losing sales on forgotten products. Kliki surfaces items from across your store based on what similar customers loved.',

    // ---- Integrations / how it works ----
    builtInConnectors: 'Plug In and Go',
    builtInDesc: 'Connect Kliki to your store in minutes — no technical team needed. Start showing smart recommendations the same day.',
    plat1Title: 'Your data, protected',
    plat1Desc: "Your store's data stays private and secure, always.",
    plat2Title: 'See results live',
    plat2Desc: 'Track sales, clicks, and activity from one simple dashboard.',
    plat3Title: 'Works everywhere',
    plat3Desc: 'Add Kliki to any store, website, or app you already run.',
    float1: 'Your Store',
    float2: 'Products',
    float3: 'Customers',
    float4: 'Sales',
    howTitle: 'Set It Up Once. Sell More Every Day.',
    chk1Title: 'Quick setup',
    chk1Desc: "Connect your store and you're live in minutes.",
    chk2Title: 'Always up to date',
    chk2Desc: 'Recommendations improve automatically as customers shop.',
    chk3Title: 'Fits any store',
    chk3Desc: 'Works with online stores, marketplaces, and apps.',
    seeDocs: 'See how it works',

    // ---- CTA ----
    readyToRev: 'Ready to Sell More?',
    scaleIntel: 'Join the Algerian stores already growing with Kliki.',
    getStartedFree: 'Try Kliki Free',
    contactSales: 'Talk to Us',

    // ---- Footer ----
    footerTagline: 'The smart recommendation tool for Algerian online stores.',
    integrations: 'Product',
    footerSolutions: 'Solutions',
    footerCompany: 'Company',
    footerDashboard: 'Dashboard',
    footerDocumentation: 'Guide',
    footerStores: 'Connected stores',
    footerRights: 'Kliki. Smart recommendations for online stores.',
    footerBadge: 'Made in Algeria 🇩🇿',

    // ---- Pricing ----
    pricingTitle: 'Simple, Transparent Pricing in Algerian Dinar',
    pricingDesc: 'Choose the plan that fits your store. Every plan is clearly priced with no hidden fees.',
    pricingPerMonth: '/month',
    pricingPerYear: '/year',
    pricingYearlySave: 'Save 16.67%',
    planBronzeDesc: 'Perfect for small boutiques and growing online stores',
    planArgentDesc: 'For growing stores with several product lines',
    planOrDesc: 'For established stores and marketplaces',
    planPlatineDesc: 'For large-scale operations and enterprise needs',
    specProducts: 'Max Products',
    specUsers: 'Active Users',
    specSupport: 'Support',
    specPerMonth: '/mo',
    supEmail: 'Email',
    supChatEmail: 'Chat + Email',
    supPriority: 'Priority',
    sup247: '24/7 Dedicated',
    getStarted: 'Get Started',
    badgePopular: 'POPULAR',
    badgeEnterprise: 'ENTERPRISE',
    pUpToProducts: 'Up to {n} products',
    pUpToUsers: 'Up to {n} active users/month',
    fRealtime: 'Real-time recommendations',
    fBasicAnalytics: 'Basic analytics dashboard',
    fEmailSupport: 'Email support',
    fApiAccess: 'API access',
    fInstantDeploy: 'Instant deployment',
    fAdvRealtime: 'Advanced real-time recommendations',
    fAdvAnalytics: 'Advanced analytics & A/B testing',
    fPriorityChat: 'Priority email & chat support',
    fWebhooks: 'Webhooks & custom events',
    fAdvApi: 'Advanced API access',
    fEngineTuning: 'Custom engine tuning',
    fMultiEngine: 'Multi-engine recommendations',
    fRealtimeInsights: 'Real-time analytics & insights',
    fPrioritySupport: 'Priority support',
    fDedicatedDash: 'Dedicated dashboard',
    fFullApiWebhooks: 'Full API access + webhooks',
    fAlgoMatching: 'Custom algorithmic matching',
    fMultiInstance: 'Manage multiple stores',
    fUnlimitedEngines: 'Unlimited recommendation engines',
    fMlInsights: 'Real-time analytics & ML insights',
    fDedicatedTeam: 'Dedicated support team',
    fCustomIntegrations: 'Custom integrations',
    fGraphql: 'Full API access + GraphQL',
    fWhiteLabel: 'White-label options',
    fSla: 'SLA guarantee',
    fCustomMl: 'Custom ML models',
    fInfraConsult: 'Infrastructure consultation',
    benefitsTitle: 'Why Choose Kliki?',
    benInstantTitle: 'Instant Deployment',
    benInstantDesc: 'No training phase. Recommendations start working immediately.',
    benAnalyticsTitle: 'Deep Analytics',
    benAnalyticsDesc: 'See how recommendations boost your conversions and revenue in real time.',
    benAccurateTitle: 'Highly Accurate',
    benAccurateDesc: 'Advanced matching shows each shopper the products they actually want.',
    benSecureTitle: 'Secure & Private',
    benSecureDesc: 'Enterprise-grade security keeps your store and customer data protected.',
    benSelfTitle: 'Self-Optimizing',
    benSelfDesc: 'Kliki adapts to changing customer tastes automatically.',
    benLocalTitle: 'Local Pricing',
    benLocalDesc: 'Billed in Algerian Dinar, built for local businesses.',
    compTitle: 'Detailed Feature Comparison',
    compFeature: 'Feature',
    compMaxProducts: 'Max Products',
    compMaxUsers: 'Max Active Users/Month',
    compRealtime: 'Real-time Recommendations',
    compAnalytics: 'Analytics',
    compSupport: 'Support',
    compCustomInt: 'Custom Integration',
    compWebhooks: 'Webhooks',
    compApiLimit: 'API Rate Limit',
    compWhiteLabel: 'White Label',
    compMultiInstance: 'Multi-Store Management',
    valNo: 'No',
    valYes: 'Yes',
    valLimited: 'Limited',
    valFull: 'Full',
    valBasic: 'Basic',
    valAdvancedAB: 'Advanced + A/B Testing',
    valRealtimeInsights: 'Real-time + Insights',
    valMlInsights: 'ML Insights',
    valStandard: 'Standard',
    valHigh: 'High',
    valVeryHigh: 'Very High',
    valCustom: 'Custom',
    valUnlimited: 'Unlimited',
    pricingCtaTitle: 'Ready to Grow Your Sales?',
    pricingCtaDesc: 'Start with Bronze and upgrade anytime as your store grows.',
    pricingCtaPrimary: 'Start Your First Store',

    // ---- Contact ----
    contactHeroTitle: 'Get in [Touch]',
    contactHeroSubtitle: "Let's talk about how Kliki can boost sales for your store.",
    contactEmailTitle: 'Email Us',
    contactChatTitle: 'Live Chat',
    contactChatValue: 'Available 9am–5pm (Algiers time)',
    contactHqTitle: 'Headquarters',
    contactHqValue: 'Algiers, Algeria 🇩🇿',
    contactFormTitle: 'Send a Message',
    contactName: 'Name',
    contactNamePh: 'Your name',
    contactEmailLabel: 'Work Email',
    contactMsg: 'How can we help?',
    contactMsgPh: 'Tell us about your store and what you need...',
    contactSend: 'Send Message',

    // ---- Login ----
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in with your email and password.',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    loginButton: 'Sign In',
    loginLoading: 'Signing in...',
    loginNoAccount: "Don't have an account?",
    loginSignupLink: 'Sign up here',
    loginFailed: 'Login failed. Please try again.',

    // ---- Signup ----
    signupTitle: 'Create your account',
    signupSubtitle: 'Start free with your email and password.',
    signupFullName: 'Full Name',
    signupFullNamePh: 'Your full name',
    signupCompany: 'Company Name',
    signupCompanyPh: 'Your store or company',
    signupButton: 'Create Account',
    signupLoading: 'Creating account...',
    signupHaveAccount: 'Already have an account?',
    signupLoginLink: 'Log in here',
    signupFailed: 'Unable to create account. Please try again.',

    // ---- Docs ----
    docsNavGettingStarted: 'Getting started',
    docsNavIntro: 'Introduction',
    docsNavHow: 'How it works',
    docsNavQuickstart: 'Quickstart',
    docsNavIntegration: 'Connect your store',
    docsNavShopify: 'Shopify plugin',
    docsNavWoo: 'Sending events',
    docsNavApi: 'REST API',
    docsNavConcepts: 'Core concepts',
    docsNavInstances: 'Connected stores',
    docsTitle: 'Kliki Guide',
    docsIntro: 'Kliki automatically shows every shopper in your store the products they are most likely to buy — in real time, with no manual work from you.',
    docsHowTitle: 'How it works',
    docsHowSubtitle: 'Smart matching, working behind the scenes',
    docsHowBody: 'Every time a customer visits your store, Kliki quietly watches what they browse and buy. It compares their behavior with other customers to spot patterns — then suggests the right product at the right moment.',
    docsHowBullet1: 'No manual rules to set up.',
    docsHowBullet2: 'Improves automatically with every visit.',
    docsHowBullet3: 'Works from your very first customer.',
    docsQuickstartTitle: 'Quickstart',
    docsQuickstartBody: 'Connect Kliki to your store in minutes using one of these three methods:',
    docsIntCard1Title: 'Shopify plugin',
    docsIntCard1Desc: 'One-click install from the Shopify App Store. No code needed.',
    docsIntCard2Title: 'Create a store',
    docsIntCard2Desc: 'Pick a plan and platform, and get your own API key in seconds.',
    docsIntCard3Title: 'REST API',
    docsIntCard3Desc: 'For custom stores — connect through our simple API.',
    docsShopifyTitle: 'Shopify plugin',
    docsShopifyBody: 'Install the Kliki plugin directly from the Shopify App Store. It automatically adds recommendations to your product pages, cart, and homepage.',
    docsWooBody: 'Send views, clicks, add-to-cart actions, and purchases to Kliki so it can learn and recommend the right products.',
    docsApiTitle: 'REST API reference',
    docsApiBody: 'For custom stores, use our REST API to track customer actions and fetch recommendations for any user or session.',
    docsInstancesTitle: 'Connected stores',
    docsInstancesBody: 'Each store you connect to Kliki gets its own dedicated recommendation environment — with a unique API key and its own private data.',

    // ---- Dashboard (common) ----
    dashHome: 'Dashboard home',
    dashWelcome: 'Welcome back',
    dashSubtitle: 'Track recommendation performance, manage your stores, and jump to the actions you use most.',
    createInstance: 'Create New Store',
    viewAllInstances: 'View All Stores',
    allHealthy: 'All stores healthy',
    engineOffline: 'Engine unreachable',
    currentAccount: 'Current account',
    noCompany: 'No company set',
    signInToLoad: 'Sign in to load your store data.',
    instancesLabel: 'Stores',
    activeLabel: 'Active',
    inactiveLabel: 'Inactive',
    loadingOverview: 'Loading your account overview...',
    tryAgain: 'Try again',
    signInToSee: 'Sign in to see your store data.',
    goToLogin: 'Go to login',
    kpiEvents: 'Events Processed',
    kpiProducts: 'Products',
    kpiActiveUsers: 'Active Users',
    kpiCtr: 'Click-Through Rate',
    kpiRevenue: 'Revenue',
    kpiClicks: 'Clicks',
    kpiConversions: 'Conversions',
    kpiAvgResponse: 'Avg Response (ms)',
    liveStats: 'Live engine activity',
    eventsByStore: 'Events by store',
    perStore: 'Per store',
    legendEvents: 'Events',
    legendClicks: 'Clicks',
    recentActivity: 'Recent activity',
    latestUpdates: 'Latest updates',
    actCreated: "New store '{name}' created",
    actCreatedDetail: '{tier} plan · created {date}',
    actEvents: '{n} events processed',
    actEventsDetail: 'Across {n} active store(s)',
    actHealthy: 'Recommendation engine connected',
    actHealthyDetail: '{a}/{b} stores active and reachable',
    actUnreachable: 'Recommendation engine unreachable',
    actUnreachableDetail: 'Showing your stores from the database. Connect the engine to see live metrics.',
    recentInstances: 'Recent stores',
    latestStores: 'Latest stores',
    viewAll: 'View all',
    storeLabel: 'Store',
    statusActive: 'Active',
    statusPending: 'Pending',
    idLabel: 'ID',
    viewDetails: 'View details',
    integrationCodeShort: 'Integration code',
    noStoresYet: 'No stores yet for this account.',
    createFirstStore: 'Create your first store',

    // ---- Dashboard (stores list) ----
    instancesTitle: 'Manage your stores',
    instancesSubtitle: 'Each store has its own recommendation engine. Create, inspect, copy integration code, or remove one here.',
    signInInstances: 'Please sign in to view your stores.',
    loadingInstances: 'Loading your stores...',
    totalInstancesLabel: 'Total stores',
    instanceNameLabel: 'Store Name',
    instanceIdLabel: 'Store ID',
    createdDateLabel: 'Created Date',
    apiKeyLabel: 'API Key',
    usageLabel: 'Usage',
    usageSuffix: 'events this month',
    revealKey: 'Reveal API Key',
    hideKey: 'Hide API Key',
    getIntegrationCode: 'Get Integration Code',
    viewDashboard: 'View Dashboard',
    deleteLabel: 'Delete',
    noInstancesYet: 'No stores yet. Create your first one to get integration code and a live dashboard.',
    deleteConfirm: 'Delete this store? This cannot be undone.',
    deleteFailed: 'Unable to delete this store.',

    // ---- Dashboard (store detail) ----
    backToInstances: 'Back to stores',
    instanceDashboardEyebrow: 'Store dashboard',
    instanceDashSubtitle: 'Live metrics from the recommendation engine for this store.',
    loadingInstanceDash: 'Loading store dashboard...',
    systemHealthEyebrow: 'System health',
    liveEngineStatus: 'Live engine status',
    mUptime: 'Uptime',
    mLatency: 'Avg latency',
    mErrorRate: 'Error rate',
    mQueued: 'Queued events',
    mHealth: 'Health',
    engineUnreachableNote: 'The recommendation engine is not reachable right now. Metrics will appear once it is connected and processing events.',
    instanceSettingsEyebrow: 'Store settings',
    apiKeyIntegration: 'API key & integration',
    showLabel: 'Show',
    hideLabelShort: 'Hide',
    copyIntegration: 'Copy integration code',
    regenerateKey: 'Regenerate key',
    regenerateNote: 'Regenerating the API key should be confirmed with a backend rotation flow before production use.',
    pasteHeaderNote: 'Copy this code and paste it into your website header, or use the plugin option on the integration page.',
    topProductsEyebrow: 'Top recommended products',
    mostSuggested: 'What gets suggested most',
    colProduct: 'Product',
    colRank: 'Rank',
    colScore: 'Score',
    noTrendingYet: 'No trending products yet. Once your store sends events, popular items appear here.',

    // ---- Dashboard (create store) ----
    superSimple: 'Super simple setup',
    createInstanceSubtitle: 'Create a store, then copy the API key and integration code right after.',
    signInCreate: 'Please sign in before creating a store.',
    instanceCreated: 'Store created',
    copyKeyOnce: 'Copy the API key now. It is shown only once.',
    integrationCodeLabel: 'Integration Code',
    copyLabel: 'Copy',
    copiedLabel: 'Copied',
    viewInstanceDash: 'View store dashboard',
    integrationPageLabel: 'Integration page',
    nextSteps: 'Next steps',
    newStep1: 'Paste the snippet into your storefront header.',
    newStep2: 'Open the store dashboard to watch health and performance.',
    newStep3: 'Use the support page if you need help.',
    websiteUrlLabel: 'Website URL',
    descriptionLabel: 'Description',
    cancelLabel: 'Cancel',
    creatingLabel: 'Creating...',
    createInstanceBtn: 'Create Store',
    createFailed: 'Unable to create store. Please try again.',
    phStoreName: 'My Fashion Store',
    phStoreDesc: "Women's clothing store",

    // ---- Dashboard (integration) ----
    integrationEyebrow: 'Integration',
    connectStoreTitle: 'Connect your store',
    integrationSubtitle: 'Three steps to get recommendations running in production.',
    signInIntegration: 'Please sign in to view your integration instructions.',
    createFirstIntegration: 'Create your first store before installing the integration.',
    pickInstance: 'Pick a store',
    apiKeyAndSnippet: 'API key & code snippet',
    intStep1: 'Copy your API key',
    intStep2: 'Add this code to your website',
    runLabel: 'Run',
    downloadLabel: 'Download',
    youreDone: "You're done",
    recsWithin24: 'Recommendations will start appearing within 24 hours.',
    integrationReady: 'Integration ready',
    supportedPlatforms: 'Supported platforms',
    chooseStack: 'Choose your stack',
    platShopifyDesc: 'Install app',
    platWooDesc: 'Download plugin',
    platCustom: 'Custom Website',
    platCustomDesc: 'Copy code snippet',
    platMagentoDesc: 'Coming soon',
    runNote: 'Paste the snippet into your site header and refresh the page to activate it.',

    // ---- Dashboard (settings) ----
    settingsEyebrow: 'Settings',
    accountPreferences: 'Account & preferences',
    settingsSubtitle: 'Update your profile, notifications, and billing defaults.',
    saveChanges: 'Save changes',
    profileInfo: 'Profile information',
    accountDetails: 'Account details',
    nameLabel: 'Name',
    companyLabel: 'Company Name',
    settingsSaved: 'Settings saved locally.',
    billingLabel: 'Billing',
    planUsage: 'Plan & usage',
    currentPlan: 'Current Plan',
    usageNote: 'Usage is tracked per store on each store dashboard.',
    upgradePlan: 'Upgrade Plan',
    notificationsLabel: 'Notifications',
    alertsReports: 'Alerts & reports',
    emailNotifications: 'Email notifications',
    weeklyReport: 'Weekly report',
    dangerZone: 'Danger zone',
    deleteAccountTitle: 'Delete account',
    deleteAccountNote: 'This action requires confirmation and permanently removes your account data.',
    deleteAccountBtn: 'Delete Account',

    // ---- Dashboard (support) ----
    supportEyebrow: 'Support',
    helpDocs: 'Help & documentation',
    supportSubtitle: 'Use the FAQ, docs, contact form, or status page when you need a hand.',
    faqEyebrow: 'FAQ',
    commonQuestions: 'Common questions',
    faqQ1: 'How long until recommendations appear?',
    faqA1: 'Usually within 24 hours after the integration code is installed and traffic starts flowing.',
    faqQ2: 'Can I use one account for multiple stores?',
    faqA2: 'Yes. Each store should use its own store so analytics and API keys stay isolated.',
    faqQ3: 'What if I need help with setup?',
    faqA3: 'Use the contact form below or open the documentation for setup and troubleshooting guidance.',
    linksEyebrow: 'Links',
    quickResources: 'Quick resources',
    documentationLabel: 'Documentation',
    contactSupport: 'Contact support',
    statusPageLabel: 'Status page',
    sendMessage: 'Send a message',
    messageLabel: 'Message',
    phMessage: 'Tell us what you need help with',

    // ---- Dashboard (sidebar) ----
    navDashboard: 'Dashboard',
    navInstances: 'Stores',
    navIntegration: 'Integration',
    navSettings: 'Settings',
    navSupport: 'Support',
    sidebarCreate: 'Create store',
    backToSite: 'Back to site',
  },
  FR: {
    // ---- Navigation / common ----
    pricing: 'Tarifs',
    docs: 'Guide',
    contact: 'Contact',
    login: 'Connexion',
    signup: 'Commencer',
    dashboard: 'Tableau de bord',

    // ---- Hero ----
    prototype: 'Recommandations intelligentes pour boutiques algériennes',
    heroTitle: 'Transformez Vos Visiteurs en [Acheteurs]',
    heroSubtitle: "Kliki affiche à chaque client les produits qu'il est le plus susceptible d'acheter — pour vendre plus sans effort supplémentaire.",
    startBuilding: 'Vendre Plus Intelligemment',
    readDocs: 'Voir Comment Ça Marche',

    // ---- Comparison ----
    whyChoose: 'Pourquoi les Boutiques Choisissent Kliki',
    whyDesc: 'Les anciens outils devinent. Kliki sait. Voilà la différence pour votre boutique.',
    classicalAI: 'Outils Traditionnels',
    kliki: 'Kliki',
    goRecommend: 'Kliki',
    trad1: 'Affiche les mêmes produits à tous les clients',
    trad2: 'Nécessite des semaines de configuration et de données',
    trad3: 'Coûteux à maintenir et à mettre à jour',
    trad4: 'Se trompe avec les nouveaux clients',
    instantLearning: 'Apprend instantanément ce que veulent vos clients',
    realTime: 'Se met à jour en temps réel à chaque visite',
    lowCompute: "Aucun coût de configuration — prêt à l'emploi",
    contextAware: "S'adapte à chaque client, à chaque visite",

    // ---- Segments / benefits ----
    builtFor: "Plus de Ventes. Moins d'Effort.",
    builtForDesc: 'Kliki travaille en silence — en affichant le bon produit, au bon client, au bon moment.',
    ecommerce: 'Augmentez le Panier Moyen',
    ecommerceDesc: "Quand un client consulte un produit, Kliki suggère immédiatement ce que des clients similaires ont acheté. Plus de pertinence, c'est un panier plus grand.",
    media: 'Faites Revenir Vos Clients',
    mediaDesc: 'Kliki retient ce que chaque client a consulté et acheté — sa prochaine visite sera personnalisée, pas aléatoire.',
    research: 'Vendez Tout Votre Catalogue',
    researchDesc: "Arrêtez de perdre des ventes sur des produits oubliés. Kliki met en avant des articles de toute votre boutique selon ce qu'ont aimé des clients similaires.",

    // ---- Integrations / how it works ----
    builtInConnectors: "Branchez et C'est Parti",
    builtInDesc: 'Connectez Kliki à votre boutique en minutes — sans équipe technique. Affichez des recommandations intelligentes dès le premier jour.',
    plat1Title: 'Vos données, protégées',
    plat1Desc: 'Les données de votre boutique restent privées et sécurisées, toujours.',
    plat2Title: 'Des résultats en direct',
    plat2Desc: 'Suivez ventes, clics et activité depuis un tableau de bord simple.',
    plat3Title: 'Fonctionne partout',
    plat3Desc: "Ajoutez Kliki à n'importe quelle boutique, site ou application.",
    float1: 'Votre Boutique',
    float2: 'Produits',
    float3: 'Clients',
    float4: 'Ventes',
    howTitle: 'Configurez Une Fois. Vendez Plus Chaque Jour.',
    chk1Title: 'Installation rapide',
    chk1Desc: 'Connectez votre boutique et soyez en ligne en minutes.',
    chk2Title: 'Toujours à jour',
    chk2Desc: "Les recommandations s'améliorent automatiquement au fil des visites.",
    chk3Title: 'Compatible avec tout',
    chk3Desc: 'Fonctionne avec boutiques en ligne, marketplaces et applications.',
    seeDocs: 'Voir comment ça marche',

    // ---- CTA ----
    readyToRev: 'Prêt à Vendre Plus ?',
    scaleIntel: 'Rejoignez les boutiques algériennes qui grandissent déjà avec Kliki.',
    getStartedFree: 'Essayer Kliki Gratuitement',
    contactSales: 'Nous Parler',

    // ---- Footer ----
    footerTagline: "L'outil de recommandation intelligent pour les boutiques algériennes en ligne.",
    integrations: 'Produit',
    footerSolutions: 'Solutions',
    footerCompany: 'Entreprise',
    footerDashboard: 'Tableau de bord',
    footerDocumentation: 'Guide',
    footerStores: 'Boutiques connectées',
    footerRights: 'Kliki. Recommandations intelligentes pour boutiques en ligne.',
    footerBadge: 'Fait en Algérie 🇩🇿',

    // ---- Pricing ----
    pricingTitle: 'Tarifs Simples et Transparents en Dinar Algérien',
    pricingDesc: 'Choisissez le plan adapté à votre boutique. Chaque plan est clairement tarifé, sans frais cachés.',
    pricingPerMonth: '/mois',
    pricingPerYear: '/an',
    pricingYearlySave: 'Économisez 16,67%',
    planBronzeDesc: 'Idéal pour les petites boutiques et les commerces en croissance',
    planArgentDesc: 'Pour les boutiques en croissance avec plusieurs gammes de produits',
    planOrDesc: 'Pour les boutiques établies et les marketplaces',
    planPlatineDesc: 'Pour les grandes opérations et les besoins entreprise',
    specProducts: 'Produits max',
    specUsers: 'Utilisateurs actifs',
    specSupport: 'Support',
    specPerMonth: '/mois',
    supEmail: 'Email',
    supChatEmail: 'Chat + Email',
    supPriority: 'Prioritaire',
    sup247: 'Dédié 24/7',
    getStarted: 'Commencer',
    badgePopular: 'POPULAIRE',
    badgeEnterprise: 'ENTREPRISE',
    pUpToProducts: "Jusqu'à {n} produits",
    pUpToUsers: "Jusqu'à {n} utilisateurs actifs/mois",
    fRealtime: 'Recommandations en temps réel',
    fBasicAnalytics: "Tableau de bord d'analyse de base",
    fEmailSupport: 'Support par email',
    fApiAccess: 'Accès API',
    fInstantDeploy: 'Déploiement instantané',
    fAdvRealtime: 'Recommandations avancées en temps réel',
    fAdvAnalytics: 'Analyses avancées et tests A/B',
    fPriorityChat: 'Support prioritaire email et chat',
    fWebhooks: 'Webhooks et événements personnalisés',
    fAdvApi: 'Accès API avancé',
    fEngineTuning: 'Réglage personnalisé du moteur',
    fMultiEngine: 'Recommandations multi-moteurs',
    fRealtimeInsights: 'Analyses et insights en temps réel',
    fPrioritySupport: 'Support prioritaire',
    fDedicatedDash: 'Tableau de bord dédié',
    fFullApiWebhooks: 'Accès API complet + webhooks',
    fAlgoMatching: 'Correspondance algorithmique personnalisée',
    fMultiInstance: 'Gérez plusieurs boutiques',
    fUnlimitedEngines: 'Moteurs de recommandation illimités',
    fMlInsights: 'Analyses temps réel et insights IA',
    fDedicatedTeam: 'Équipe de support dédiée',
    fCustomIntegrations: 'Intégrations personnalisées',
    fGraphql: 'Accès API complet + GraphQL',
    fWhiteLabel: 'Options marque blanche',
    fSla: 'Garantie SLA',
    fCustomMl: 'Modèles IA personnalisés',
    fInfraConsult: 'Conseil en infrastructure',
    benefitsTitle: 'Pourquoi Choisir Kliki ?',
    benInstantTitle: 'Déploiement Instantané',
    benInstantDesc: "Aucune phase d'apprentissage. Les recommandations fonctionnent immédiatement.",
    benAnalyticsTitle: 'Analyses Approfondies',
    benAnalyticsDesc: 'Voyez comment les recommandations augmentent vos conversions et vos revenus en temps réel.',
    benAccurateTitle: 'Très Précis',
    benAccurateDesc: "Une correspondance avancée montre à chaque client les produits qu'il veut vraiment.",
    benSecureTitle: 'Sécurisé et Privé',
    benSecureDesc: 'Une sécurité de niveau entreprise protège votre boutique et vos données clients.',
    benSelfTitle: 'Auto-Optimisé',
    benSelfDesc: "Kliki s'adapte automatiquement aux goûts changeants des clients.",
    benLocalTitle: 'Tarifs Locaux',
    benLocalDesc: 'Facturé en Dinar Algérien, conçu pour les entreprises locales.',
    compTitle: 'Comparaison Détaillée des Fonctionnalités',
    compFeature: 'Fonctionnalité',
    compMaxProducts: 'Produits max',
    compMaxUsers: 'Utilisateurs actifs max/mois',
    compRealtime: 'Recommandations en temps réel',
    compAnalytics: 'Analyses',
    compSupport: 'Support',
    compCustomInt: 'Intégration personnalisée',
    compWebhooks: 'Webhooks',
    compApiLimit: 'Limite de débit API',
    compWhiteLabel: 'Marque blanche',
    compMultiInstance: 'Gestion multi-boutiques',
    valNo: 'Non',
    valYes: 'Oui',
    valLimited: 'Limité',
    valFull: 'Complet',
    valBasic: 'De base',
    valAdvancedAB: 'Avancé + Tests A/B',
    valRealtimeInsights: 'Temps réel + Insights',
    valMlInsights: 'Insights IA',
    valStandard: 'Standard',
    valHigh: 'Élevé',
    valVeryHigh: 'Très élevé',
    valCustom: 'Personnalisé',
    valUnlimited: 'Illimité',
    pricingCtaTitle: 'Prêt à Augmenter Vos Ventes ?',
    pricingCtaDesc: 'Commencez avec Bronze et évoluez à tout moment, au rythme de votre boutique.',
    pricingCtaPrimary: 'Connecter Votre Boutique',

    // ---- Contact ----
    contactHeroTitle: '[Contactez]-Nous',
    contactHeroSubtitle: 'Discutons de la façon dont Kliki peut augmenter les ventes de votre boutique.',
    contactEmailTitle: 'Écrivez-nous',
    contactChatTitle: 'Chat en Direct',
    contactChatValue: "Disponible 9h–17h (heure d'Alger)",
    contactHqTitle: 'Siège',
    contactHqValue: 'Alger, Algérie 🇩🇿',
    contactFormTitle: 'Envoyer un Message',
    contactName: 'Nom',
    contactNamePh: 'Votre nom',
    contactEmailLabel: 'Email professionnel',
    contactMsg: 'Comment pouvons-nous aider ?',
    contactMsgPh: 'Parlez-nous de votre boutique et de vos besoins...',
    contactSend: 'Envoyer le Message',

    // ---- Login ----
    loginTitle: 'Bon retour',
    loginSubtitle: 'Connectez-vous avec votre email et mot de passe.',
    emailLabel: 'Email',
    passwordLabel: 'Mot de passe',
    loginButton: 'Se connecter',
    loginLoading: 'Connexion...',
    loginNoAccount: "Vous n'avez pas de compte ?",
    loginSignupLink: 'Inscrivez-vous ici',
    loginFailed: 'Échec de la connexion. Veuillez réessayer.',

    // ---- Signup ----
    signupTitle: 'Créez votre compte',
    signupSubtitle: 'Commencez gratuitement avec votre email et mot de passe.',
    signupFullName: 'Nom complet',
    signupFullNamePh: 'Votre nom complet',
    signupCompany: "Nom de l'entreprise",
    signupCompanyPh: 'Votre boutique ou entreprise',
    signupButton: 'Créer le Compte',
    signupLoading: 'Création du compte...',
    signupHaveAccount: 'Vous avez déjà un compte ?',
    signupLoginLink: 'Connectez-vous ici',
    signupFailed: 'Impossible de créer le compte. Veuillez réessayer.',

    // ---- Docs ----
    docsNavGettingStarted: 'Démarrage',
    docsNavIntro: 'Introduction',
    docsNavHow: 'Comment ça marche',
    docsNavQuickstart: 'Démarrage rapide',
    docsNavIntegration: 'Connecter votre boutique',
    docsNavShopify: 'Extension Shopify',
    docsNavWoo: 'Envoi des événements',
    docsNavApi: 'API REST',
    docsNavConcepts: 'Concepts clés',
    docsNavInstances: 'Boutiques connectées',
    docsTitle: 'Guide Kliki',
    docsIntro: "Kliki affiche automatiquement à chaque client de votre boutique les produits qu'il est le plus susceptible d'acheter — en temps réel, sans aucun travail manuel de votre part.",
    docsHowTitle: 'Comment ça marche',
    docsHowSubtitle: 'Une correspondance intelligente, en coulisses',
    docsHowBody: "À chaque visite d'un client, Kliki observe discrètement ce qu'il parcourt et achète. Il compare son comportement à celui d'autres clients pour trouver des tendances — et suggère le bon produit au bon moment.",
    docsHowBullet1: 'Aucune règle manuelle à configurer.',
    docsHowBullet2: "S'améliore automatiquement à chaque visite.",
    docsHowBullet3: 'Fonctionne dès le premier client.',
    docsQuickstartTitle: 'Démarrage rapide',
    docsQuickstartBody: 'Connectez Kliki à votre boutique en minutes avec une de ces trois méthodes :',
    docsIntCard1Title: 'Extension Shopify',
    docsIntCard1Desc: "Installation en un clic depuis l'App Store Shopify. Sans code.",
    docsIntCard2Title: 'Créer une boutique',
    docsIntCard2Desc: 'Choisissez un plan et une plateforme, et obtenez votre clé API en quelques secondes.',
    docsIntCard3Title: 'API REST',
    docsIntCard3Desc: 'Pour les boutiques personnalisées — connectez-vous via notre API simple.',
    docsShopifyTitle: 'Extension Shopify',
    docsShopifyBody: "Installez l'extension Kliki directement depuis l'App Store Shopify. Elle ajoute automatiquement des recommandations sur vos pages produits, votre panier et votre page d'accueil.",
    docsWooBody: "Envoyez à Kliki les vues, clics, ajouts au panier et achats pour qu'il apprenne et recommande les bons produits.",
    docsApiTitle: 'Référence API REST',
    docsApiBody: 'Pour les boutiques personnalisées, utilisez notre API REST pour suivre les actions des clients et récupérer des recommandations pour chaque utilisateur ou session.',
    docsInstancesTitle: 'Boutiques connectées',
    docsInstancesBody: 'Chaque boutique que vous connectez à Kliki obtient son propre environnement de recommandation dédié — avec une clé API unique et ses propres données privées.',

    // ---- Dashboard (common) ----
    dashHome: 'Accueil du tableau de bord',
    dashWelcome: 'Bon retour',
    dashSubtitle: 'Suivez les performances des recommandations, gérez vos boutiques et accédez vite aux actions clés.',
    createInstance: 'Créer une Boutique',
    viewAllInstances: 'Voir Toutes les Boutiques',
    allHealthy: 'Toutes les boutiques sont saines',
    engineOffline: 'Moteur injoignable',
    currentAccount: 'Compte actuel',
    noCompany: 'Aucune entreprise définie',
    signInToLoad: 'Connectez-vous pour charger les données de votre boutique.',
    instancesLabel: 'Boutiques',
    activeLabel: 'Actives',
    inactiveLabel: 'Inactives',
    loadingOverview: 'Chargement de votre aperçu...',
    tryAgain: 'Réessayer',
    signInToSee: 'Connectez-vous pour voir les données de votre boutique.',
    goToLogin: 'Aller à la connexion',
    kpiEvents: 'Événements traités',
    kpiProducts: 'Produits',
    kpiActiveUsers: 'Utilisateurs actifs',
    kpiCtr: 'Taux de clics',
    kpiRevenue: 'Revenu',
    kpiClicks: 'Clics',
    kpiConversions: 'Conversions',
    kpiAvgResponse: 'Réponse moy. (ms)',
    liveStats: 'Activité du moteur en direct',
    eventsByStore: 'Événements par boutique',
    perStore: 'Par boutique',
    legendEvents: 'Événements',
    legendClicks: 'Clics',
    recentActivity: 'Activité récente',
    latestUpdates: 'Dernières nouveautés',
    actCreated: "Nouvelle boutique '{name}' créée",
    actCreatedDetail: 'Plan {tier} · créée le {date}',
    actEvents: '{n} événements traités',
    actEventsDetail: 'Sur {n} boutique(s) active(s)',
    actHealthy: 'Moteur de recommandation connecté',
    actHealthyDetail: '{a}/{b} boutiques actives et joignables',
    actUnreachable: 'Moteur de recommandation injoignable',
    actUnreachableDetail: 'Affichage de vos boutiques depuis la base de données. Connectez le moteur pour voir les métriques en direct.',
    recentInstances: 'Boutiques récentes',
    latestStores: 'Dernières boutiques',
    viewAll: 'Voir tout',
    storeLabel: 'Boutique',
    statusActive: 'Active',
    statusPending: 'En attente',
    idLabel: 'ID',
    viewDetails: 'Voir les détails',
    integrationCodeShort: "Code d'intégration",
    noStoresYet: 'Aucune boutique pour ce compte.',
    createFirstStore: 'Créez votre première boutique',

    // ---- Dashboard (stores list) ----
    instancesTitle: 'Gérez vos boutiques',
    instancesSubtitle: 'Chaque boutique a son propre moteur de recommandation. Créez, inspectez, copiez le code ou supprimez-en une ici.',
    signInInstances: 'Connectez-vous pour voir vos boutiques.',
    loadingInstances: 'Chargement de vos boutiques...',
    totalInstancesLabel: 'Total boutiques',
    instanceNameLabel: 'Nom de la boutique',
    instanceIdLabel: 'ID de la boutique',
    createdDateLabel: 'Date de création',
    apiKeyLabel: 'Clé API',
    usageLabel: 'Usage',
    usageSuffix: 'événements ce mois-ci',
    revealKey: 'Afficher la clé API',
    hideKey: 'Masquer la clé API',
    getIntegrationCode: "Obtenir le code d'intégration",
    viewDashboard: 'Voir le tableau de bord',
    deleteLabel: 'Supprimer',
    noInstancesYet: 'Aucune boutique. Créez la première pour obtenir le code et un tableau de bord en direct.',
    deleteConfirm: 'Supprimer cette boutique ? Action irréversible.',
    deleteFailed: 'Impossible de supprimer cette boutique.',

    // ---- Dashboard (store detail) ----
    backToInstances: 'Retour aux boutiques',
    instanceDashboardEyebrow: 'Tableau de bord boutique',
    instanceDashSubtitle: 'Métriques en direct du moteur de recommandation pour cette boutique.',
    loadingInstanceDash: 'Chargement du tableau de bord...',
    systemHealthEyebrow: 'État du système',
    liveEngineStatus: 'État du moteur en direct',
    mUptime: 'Disponibilité',
    mLatency: 'Latence moy.',
    mErrorRate: "Taux d'erreur",
    mQueued: "Événements en file",
    mHealth: 'Santé',
    engineUnreachableNote: "Le moteur de recommandation est injoignable pour le moment. Les métriques apparaîtront une fois connecté et en traitement.",
    instanceSettingsEyebrow: 'Paramètres de la boutique',
    apiKeyIntegration: 'Clé API et intégration',
    showLabel: 'Afficher',
    hideLabelShort: 'Masquer',
    copyIntegration: "Copier le code d'intégration",
    regenerateKey: 'Régénérer la clé',
    regenerateNote: "La régénération de la clé API doit être confirmée par un processus de rotation côté backend avant la production.",
    pasteHeaderNote: "Copiez ce code dans l'en-tête de votre site, ou utilisez l'option plugin sur la page d'intégration.",
    topProductsEyebrow: 'Produits les plus recommandés',
    mostSuggested: 'Ce qui est le plus suggéré',
    colProduct: 'Produit',
    colRank: 'Rang',
    colScore: 'Score',
    noTrendingYet: "Aucun produit tendance pour l'instant. Dès que votre boutique envoie des événements, les articles populaires apparaîtront ici.",

    // ---- Dashboard (create store) ----
    superSimple: 'Configuration ultra simple',
    createInstanceSubtitle: "Créez une boutique, puis copiez la clé API et le code d'intégration juste après.",
    signInCreate: 'Connectez-vous avant de créer une boutique.',
    instanceCreated: 'Boutique créée',
    copyKeyOnce: "Copiez la clé API maintenant. Elle n'est affichée qu'une seule fois.",
    integrationCodeLabel: "Code d'intégration",
    copyLabel: 'Copier',
    copiedLabel: 'Copié',
    viewInstanceDash: 'Voir le tableau de bord',
    integrationPageLabel: "Page d'intégration",
    nextSteps: 'Étapes suivantes',
    newStep1: "Collez le snippet dans l'en-tête de votre boutique.",
    newStep2: 'Ouvrez le tableau de bord pour suivre la santé et les performances.',
    newStep3: "Utilisez la page de support si vous avez besoin d'aide.",
    websiteUrlLabel: 'URL du site',
    descriptionLabel: 'Description',
    cancelLabel: 'Annuler',
    creatingLabel: 'Création...',
    createInstanceBtn: 'Créer la Boutique',
    createFailed: 'Impossible de créer la boutique. Réessayez.',
    phStoreName: 'Ma Boutique Mode',
    phStoreDesc: 'Boutique de vêtements pour femmes',

    // ---- Dashboard (integration) ----
    integrationEyebrow: 'Intégration',
    connectStoreTitle: 'Connectez votre boutique',
    integrationSubtitle: 'Trois étapes pour lancer les recommandations en production.',
    signInIntegration: "Connectez-vous pour voir vos instructions d'intégration.",
    createFirstIntegration: "Créez votre première boutique avant d'installer l'intégration.",
    pickInstance: 'Choisir une boutique',
    apiKeyAndSnippet: 'Clé API et code',
    intStep1: 'Copiez votre clé API',
    intStep2: 'Ajoutez ce code à votre site',
    runLabel: 'Exécuter',
    downloadLabel: 'Télécharger',
    youreDone: "C'est terminé",
    recsWithin24: 'Les recommandations apparaîtront sous 24 heures.',
    integrationReady: 'Intégration prête',
    supportedPlatforms: 'Plateformes prises en charge',
    chooseStack: 'Choisissez votre stack',
    platShopifyDesc: "Installer l'app",
    platWooDesc: 'Télécharger le plugin',
    platCustom: 'Site personnalisé',
    platCustomDesc: 'Copier le code',
    platMagentoDesc: 'Bientôt disponible',
    runNote: "Collez le snippet dans l'en-tête de votre site et rafraîchissez la page pour l'activer.",

    // ---- Dashboard (settings) ----
    settingsEyebrow: 'Paramètres',
    accountPreferences: 'Compte et préférences',
    settingsSubtitle: 'Mettez à jour votre profil, vos notifications et vos paramètres de facturation.',
    saveChanges: 'Enregistrer',
    profileInfo: 'Informations du profil',
    accountDetails: 'Détails du compte',
    nameLabel: 'Nom',
    companyLabel: "Nom de l'entreprise",
    settingsSaved: 'Paramètres enregistrés localement.',
    billingLabel: 'Facturation',
    planUsage: 'Plan et usage',
    currentPlan: 'Plan actuel',
    usageNote: "L'usage est suivi par boutique sur chaque tableau de bord.",
    upgradePlan: 'Améliorer le plan',
    notificationsLabel: 'Notifications',
    alertsReports: 'Alertes et rapports',
    emailNotifications: 'Notifications par email',
    weeklyReport: 'Rapport hebdomadaire',
    dangerZone: 'Zone dangereuse',
    deleteAccountTitle: 'Supprimer le compte',
    deleteAccountNote: 'Cette action nécessite une confirmation et supprime définitivement les données de votre compte.',
    deleteAccountBtn: 'Supprimer le Compte',

    // ---- Dashboard (support) ----
    supportEyebrow: 'Support',
    helpDocs: 'Aide et documentation',
    supportSubtitle: "Utilisez la FAQ, la doc, le formulaire ou la page d'état quand vous avez besoin d'aide.",
    faqEyebrow: 'FAQ',
    commonQuestions: 'Questions fréquentes',
    faqQ1: 'Combien de temps avant que les recommandations apparaissent ?',
    faqA1: "Généralement sous 24 heures après l'installation du code et le début du trafic.",
    faqQ2: 'Puis-je utiliser un compte pour plusieurs boutiques ?',
    faqA2: 'Oui. Chaque boutique doit utiliser sa propre instance pour isoler analyses et clés API.',
    faqQ3: "Et si j'ai besoin d'aide pour la configuration ?",
    faqA3: 'Utilisez le formulaire ci-dessous ou ouvrez la documentation pour la configuration et le dépannage.',
    linksEyebrow: 'Liens',
    quickResources: 'Ressources rapides',
    documentationLabel: 'Documentation',
    contactSupport: 'Contacter le support',
    statusPageLabel: "Page d'état",
    sendMessage: 'Envoyer un message',
    messageLabel: 'Message',
    phMessage: "Dites-nous ce dont vous avez besoin",

    // ---- Dashboard (sidebar) ----
    navDashboard: 'Tableau de bord',
    navInstances: 'Boutiques',
    navIntegration: 'Intégration',
    navSettings: 'Paramètres',
    navSupport: 'Support',
    sidebarCreate: 'Créer une boutique',
    backToSite: 'Retour au site',
  },
  AR: {
    // ---- Navigation / common ----
    pricing: 'الأسعار',
    docs: 'الدليل',
    contact: 'تواصل معنا',
    login: 'تسجيل الدخول',
    signup: 'ابدأ مجانًا',
    dashboard: 'لوحة التحكم',

    // ---- Hero ----
    prototype: 'توصيات ذكية للمتاجر الجزائرية',
    heroTitle: 'حوّل زوار متجرك إلى [مشترين فعليين]',
    heroSubtitle: 'كليكي يعرض لكل زبون المنتجات اللي يحتمل يشتريها — تبيع أكثر بدون مجهود إضافي.',
    startBuilding: 'ابدأ تبيع أذكى',
    readDocs: 'شوف كيفاش يخدم',

    // ---- Comparison ----
    whyChoose: 'علاش أصحاب المتاجر يختارون كليكي',
    whyDesc: 'الأدوات القديمة تخمّن. كليكي يعرف. هذا هو الفرق لمتجرك.',
    classicalAI: 'الأدوات التقليدية',
    kliki: 'كليكي',
    goRecommend: 'كليكي',
    trad1: 'يعرض نفس المنتجات لكل الزبائن',
    trad2: 'يحتاج أسابيع من الإعداد وجمع البيانات',
    trad3: 'مكلف في الصيانة والتحديث',
    trad4: 'يخطئ مع الزبائن الجدد',
    instantLearning: 'يفهم ما يريده زبائنك من أول زيارة',
    realTime: 'يتحدّث مع كل زيارة جديدة',
    lowCompute: 'بدون إعداد — يشتغل مباشرة',
    contextAware: 'يتكيّف مع كل زبون في كل مرة',

    // ---- Segments / benefits ----
    builtFor: 'مبيعات أكثر. مجهود أقل.',
    builtForDesc: 'كليكي يشتغل في الخلفية — يعرض المنتج الصح للزبون الصح في اللحظة الصح.',
    ecommerce: 'زيد قيمة كل طلبية',
    ecommerceDesc: 'كي زبون يشوف منتج، كليكي يقترح له على طول ما اشتراه زبائن مشابهين. اقتراحات أدق = سلة أكبر.',
    media: 'خلي زبائنك يرجعو',
    mediaDesc: 'كليكي يتذكر ما تصفحه كل زبون واشتراه — في الزيارة الجاية يشوف المنتجات اللي تهمو حقًا.',
    research: 'بيع من كامل كتالوجك',
    researchDesc: 'وقف تخسر مبيعات على منتجات منسية. كليكي يبرز منتجات من كل ركن في متجرك بناءً على ما أحبه زبائن مشابهين.',

    // ---- Integrations / how it works ----
    builtInConnectors: 'وصّل وابدأ',
    builtInDesc: 'وصّل كليكي بمتجرك في دقائق — بدون فريق تقني. ابدأ تعرض توصيات ذكية من نفس اليوم.',
    plat1Title: 'بياناتك محمية',
    plat1Desc: 'بيانات متجرك تبقى خاصة وآمنة دائمًا.',
    plat2Title: 'نتائج مباشرة',
    plat2Desc: 'تابع المبيعات والنقرات والنشاط من لوحة تحكم بسيطة.',
    plat3Title: 'يشتغل في كل مكان',
    plat3Desc: 'أضف كليكي لأي متجر أو موقع أو تطبيق عندك.',
    float1: 'متجرك',
    float2: 'المنتجات',
    float3: 'الزبائن',
    float4: 'المبيعات',
    howTitle: 'نصّبو مرة وحدة. بيع أكثر كل يوم.',
    chk1Title: 'تنصيب سريع',
    chk1Desc: 'وصّل متجرك وتكون متصل في دقائق.',
    chk2Title: 'محدّث دائمًا',
    chk2Desc: 'التوصيات تتحسن تلقائيًا كي يتسوّقو الزبائن.',
    chk3Title: 'يناسب أي متجر',
    chk3Desc: 'يشتغل مع المتاجر الإلكترونية والأسواق والتطبيقات.',
    seeDocs: 'شوف كيفاش يخدم',

    // ---- CTA ----
    readyToRev: 'مستعد تبيع أكثر؟',
    scaleIntel: 'انضم لأصحاب المتاجر الجزائرية اللي كبرو مع كليكي.',
    getStartedFree: 'جرب كليكي مجانًا',
    contactSales: 'تواصل معنا',

    // ---- Footer ----
    footerTagline: 'أداة التوصيات الذكية للمتاجر الإلكترونية الجزائرية.',
    integrations: 'المنتج',
    footerSolutions: 'الحلول',
    footerCompany: 'الشركة',
    footerDashboard: 'لوحة التحكم',
    footerDocumentation: 'الدليل',
    footerStores: 'المتاجر المربوطة',
    footerRights: 'كليكي. توصيات ذكية للمتاجر الإلكترونية.',
    footerBadge: 'صُنع في الجزائر 🇩🇿',

    // ---- Pricing ----
    pricingTitle: 'أسعار بسيطة وشفافة بالدينار الجزائري',
    pricingDesc: 'اختر الخطة اللي تناسب متجرك. كل خطة سعرها واضح وبدون رسوم خفية.',
    pricingPerMonth: '/شهر',
    pricingPerYear: '/سنة',
    pricingYearlySave: 'وفّر 16.67%',
    planBronzeDesc: 'مثالي للمتاجر الصغيرة والمتاجر اللي راها تكبر',
    planArgentDesc: 'للمتاجر اللي تكبر وعندها عدة أنواع منتجات',
    planOrDesc: 'للمتاجر الراسخة والأسواق الإلكترونية',
    planPlatineDesc: 'للعمليات الكبيرة واحتياجات المؤسسات',
    specProducts: 'أقصى عدد منتجات',
    specUsers: 'مستخدمون نشطون',
    specSupport: 'الدعم',
    specPerMonth: '/شهر',
    supEmail: 'إيميل',
    supChatEmail: 'دردشة + إيميل',
    supPriority: 'أولوية',
    sup247: 'مخصص 24/7',
    getStarted: 'ابدأ الآن',
    badgePopular: 'الأكثر طلبًا',
    badgeEnterprise: 'مؤسسات',
    pUpToProducts: 'حتى {n} منتج',
    pUpToUsers: 'حتى {n} مستخدم نشط/شهر',
    fRealtime: 'توصيات فورية',
    fBasicAnalytics: 'لوحة تحليلات أساسية',
    fEmailSupport: 'دعم عبر الإيميل',
    fApiAccess: 'وصول إلى الـ API',
    fInstantDeploy: 'تفعيل فوري',
    fAdvRealtime: 'توصيات فورية متقدمة',
    fAdvAnalytics: 'تحليلات متقدمة واختبار A/B',
    fPriorityChat: 'دعم بأولوية عبر الإيميل والدردشة',
    fWebhooks: 'Webhooks وأحداث مخصصة',
    fAdvApi: 'وصول API متقدم',
    fEngineTuning: 'ضبط مخصص للمحرك',
    fMultiEngine: 'توصيات متعددة المحركات',
    fRealtimeInsights: 'تحليلات ورؤى فورية',
    fPrioritySupport: 'دعم بأولوية',
    fDedicatedDash: 'لوحة تحكم مخصصة',
    fFullApiWebhooks: 'وصول API كامل + webhooks',
    fAlgoMatching: 'مطابقة خوارزمية مخصصة',
    fMultiInstance: 'إدارة عدة متاجر',
    fUnlimitedEngines: 'محركات توصية بلا حدود',
    fMlInsights: 'تحليلات فورية ورؤى الذكاء الاصطناعي',
    fDedicatedTeam: 'فريق دعم مخصص',
    fCustomIntegrations: 'تكاملات مخصصة',
    fGraphql: 'وصول API كامل + GraphQL',
    fWhiteLabel: 'خيارات العلامة البيضاء',
    fSla: 'ضمان SLA',
    fCustomMl: 'نماذج ذكاء اصطناعي مخصصة',
    fInfraConsult: 'استشارة البنية التحتية',
    benefitsTitle: 'علاش تختار كليكي؟',
    benInstantTitle: 'تفعيل فوري',
    benInstantDesc: 'بدون مرحلة تدريب. التوصيات تخدم على طول.',
    benAnalyticsTitle: 'تحليلات معمّقة',
    benAnalyticsDesc: 'شوف كيفاش التوصيات تزيد مبيعاتك وأرباحك في الوقت الحقيقي.',
    benAccurateTitle: 'دقّة عالية',
    benAccurateDesc: 'مطابقة متقدمة تعرض لكل زبون المنتجات اللي يبغيها فعلاً.',
    benSecureTitle: 'آمن وخاص',
    benSecureDesc: 'أمان بمستوى المؤسسات يحمي متجرك وبيانات زبائنك.',
    benSelfTitle: 'يحسّن نفسه',
    benSelfDesc: 'كليكي يتكيّف تلقائيًا مع تغيّر أذواق الزبائن.',
    benLocalTitle: 'أسعار محلية',
    benLocalDesc: 'الفوترة بالدينار الجزائري، مصمّم للشركات المحلية.',
    compTitle: 'مقارنة مفصّلة للميزات',
    compFeature: 'الميزة',
    compMaxProducts: 'أقصى عدد منتجات',
    compMaxUsers: 'أقصى مستخدمين نشطين/شهر',
    compRealtime: 'توصيات فورية',
    compAnalytics: 'التحليلات',
    compSupport: 'الدعم',
    compCustomInt: 'تكامل مخصص',
    compWebhooks: 'Webhooks',
    compApiLimit: 'حد معدل الـ API',
    compWhiteLabel: 'العلامة البيضاء',
    compMultiInstance: 'إدارة عدة متاجر',
    valNo: 'لا',
    valYes: 'نعم',
    valLimited: 'محدود',
    valFull: 'كامل',
    valBasic: 'أساسي',
    valAdvancedAB: 'متقدم + اختبار A/B',
    valRealtimeInsights: 'فوري + رؤى',
    valMlInsights: 'رؤى الذكاء الاصطناعي',
    valStandard: 'قياسي',
    valHigh: 'عالي',
    valVeryHigh: 'عالي جدًا',
    valCustom: 'مخصص',
    valUnlimited: 'بلا حدود',
    pricingCtaTitle: 'مستعد تزيد مبيعاتك؟',
    pricingCtaDesc: 'ابدأ بخطة برونز وطوّر في أي وقت كي يكبر متجرك.',
    pricingCtaPrimary: 'ابدأ متجرك الأول',

    // ---- Contact ----
    contactHeroTitle: '[تواصل] معنا',
    contactHeroSubtitle: 'نحكيو كيفاش كليكي يقدر يزيد مبيعات متجرك.',
    contactEmailTitle: 'راسلنا',
    contactChatTitle: 'دردشة مباشرة',
    contactChatValue: 'متاح من 9 صباحًا إلى 5 مساءً (توقيت الجزائر)',
    contactHqTitle: 'المقر',
    contactHqValue: 'الجزائر العاصمة 🇩🇿',
    contactFormTitle: 'أرسل رسالة',
    contactName: 'الاسم',
    contactNamePh: 'اسمك',
    contactEmailLabel: 'البريد المهني',
    contactMsg: 'كيفاش نقدرو نعاونوك؟',
    contactMsgPh: 'حدّثنا عن متجرك وما تحتاجه...',
    contactSend: 'إرسال الرسالة',

    // ---- Login ----
    loginTitle: 'مرحبًا بعودتك',
    loginSubtitle: 'سجّل الدخول بالإيميل وكلمة السر.',
    emailLabel: 'البريد الإلكتروني',
    passwordLabel: 'كلمة السر',
    loginButton: 'تسجيل الدخول',
    loginLoading: 'جارٍ الدخول...',
    loginNoAccount: 'ماعندكش حساب؟',
    loginSignupLink: 'سجّل هنا',
    loginFailed: 'فشل تسجيل الدخول. حاول مرة أخرى.',

    // ---- Signup ----
    signupTitle: 'أنشئ حسابك',
    signupSubtitle: 'ابدأ مجانًا بالإيميل وكلمة السر.',
    signupFullName: 'الاسم الكامل',
    signupFullNamePh: 'اسمك الكامل',
    signupCompany: 'اسم الشركة',
    signupCompanyPh: 'متجرك أو شركتك',
    signupButton: 'إنشاء الحساب',
    signupLoading: 'جارٍ إنشاء الحساب...',
    signupHaveAccount: 'عندك حساب؟',
    signupLoginLink: 'سجّل الدخول هنا',
    signupFailed: 'تعذّر إنشاء الحساب. حاول مرة أخرى.',

    // ---- Docs ----
    docsNavGettingStarted: 'البداية',
    docsNavIntro: 'مقدمة',
    docsNavHow: 'كيفاش يشتغل',
    docsNavQuickstart: 'بداية سريعة',
    docsNavIntegration: 'اربط متجرك',
    docsNavShopify: 'إضافة Shopify',
    docsNavWoo: 'إرسال الأحداث',
    docsNavApi: 'الـ API',
    docsNavConcepts: 'المفاهيم الأساسية',
    docsNavInstances: 'المتاجر المربوطة',
    docsTitle: 'دليل كليكي',
    docsIntro: 'كليكي يعرض لكل زبون في متجرك المنتجات اللي يحتمل يشتريها — في الوقت الحقيقي، بدون ما تدير شي من عندك.',
    docsHowTitle: 'كيفاش يشتغل',
    docsHowSubtitle: 'ذكاء يشتغل في الخلفية',
    docsHowBody: 'كي زبون يزور متجرك، كليكي يراقب بهدوء ما يتصفحه وما يشتريه. يحلل سلوكه ويقارنه بزبائن مشابهين — ومن هنا يقدر يقترح المنتج الصح في اللحظة الصح.',
    docsHowBullet1: 'بدون قواعد يدوية تحتاج تحددها.',
    docsHowBullet2: 'يتحسن تلقائيًا مع كل زيارة.',
    docsHowBullet3: 'يشتغل من أول زبون.',
    docsQuickstartTitle: 'بداية سريعة',
    docsQuickstartBody: 'اربط كليكي بمتجرك في دقائق باستخدام إحدى الطرق التالية:',
    docsIntCard1Title: 'إضافة Shopify',
    docsIntCard1Desc: 'تنصيب بنقرة واحدة من متجر تطبيقات Shopify. بدون كود.',
    docsIntCard2Title: 'أنشئ متجرًا',
    docsIntCard2Desc: 'اختر خطة ومنصة، واحصل على مفتاح API خاص بك في ثوانٍ.',
    docsIntCard3Title: 'الـ API',
    docsIntCard3Desc: 'للمتاجر المخصصة — اربط عبر الـ API البسيط تاعنا.',
    docsShopifyTitle: 'إضافة Shopify',
    docsShopifyBody: 'نصّب إضافة كليكي مباشرة من متجر تطبيقات Shopify. بعد التنصيب، تضيف توصيات تلقائيًا على صفحات المنتجات، السلة، والصفحة الرئيسية.',
    docsWooBody: 'أرسل لكليكي المشاهدات والنقرات والإضافات للسلة والمشتريات حتى يتعلّم ويقترح المنتجات الصحيحة.',
    docsApiTitle: 'مرجع الـ API',
    docsApiBody: 'للمتاجر المخصصة، استخدم الـ API تاعنا لتتبع تصرفات الزبائن واسترجاع التوصيات لأي مستخدم أو جلسة.',
    docsInstancesTitle: 'المتاجر المربوطة',
    docsInstancesBody: 'كل متجر تربطه بكليكي يحصل على بيئة توصيات خاصة به — بمفتاح API فريد وبياناته الخاصة.',

    // ---- Dashboard (common) ----
    dashHome: 'الصفحة الرئيسية للوحة',
    dashWelcome: 'مرحبًا بعودتك',
    dashSubtitle: 'تابع أداء التوصيات، أدِر متاجرك، وانتقل بسرعة للإجراءات الأكثر استخدامًا.',
    createInstance: 'إنشاء متجر جديد',
    viewAllInstances: 'عرض كل المتاجر',
    allHealthy: 'كل المتاجر تعمل جيدًا',
    engineOffline: 'المحرك غير متاح',
    currentAccount: 'الحساب الحالي',
    noCompany: 'لا توجد شركة محددة',
    signInToLoad: 'سجّل الدخول لتحميل بيانات متجرك.',
    instancesLabel: 'المتاجر',
    activeLabel: 'نشطة',
    inactiveLabel: 'غير نشطة',
    loadingOverview: 'جارٍ تحميل نظرة عامة على حسابك...',
    tryAgain: 'حاول مرة أخرى',
    signInToSee: 'سجّل الدخول لرؤية بيانات متجرك.',
    goToLogin: 'الذهاب لتسجيل الدخول',
    kpiEvents: 'الأحداث المعالَجة',
    kpiProducts: 'المنتجات',
    kpiActiveUsers: 'المستخدمون النشطون',
    kpiCtr: 'معدل النقر',
    kpiRevenue: 'الإيرادات',
    kpiClicks: 'النقرات',
    kpiConversions: 'التحويلات',
    kpiAvgResponse: 'متوسط الاستجابة (مل.ث)',
    liveStats: 'نشاط المحرك المباشر',
    eventsByStore: 'الأحداث حسب المتجر',
    perStore: 'لكل متجر',
    legendEvents: 'الأحداث',
    legendClicks: 'النقرات',
    recentActivity: 'النشاط الأخير',
    latestUpdates: 'آخر التحديثات',
    actCreated: "تم إنشاء متجر جديد '{name}'",
    actCreatedDetail: 'خطة {tier} · أُنشئ في {date}',
    actEvents: 'تمت معالجة {n} حدث',
    actEventsDetail: 'عبر {n} متجر نشط',
    actHealthy: 'محرك التوصيات متصل',
    actHealthyDetail: '{a}/{b} متجر نشط ومتاح',
    actUnreachable: 'محرك التوصيات غير متاح',
    actUnreachableDetail: 'يتم عرض متاجرك من قاعدة البيانات. اربط المحرك لرؤية المقاييس المباشرة.',
    recentInstances: 'المتاجر الأخيرة',
    latestStores: 'أحدث المتاجر',
    viewAll: 'عرض الكل',
    storeLabel: 'متجر',
    statusActive: 'نشط',
    statusPending: 'قيد الانتظار',
    idLabel: 'المعرّف',
    viewDetails: 'عرض التفاصيل',
    integrationCodeShort: 'كود التوصيل',
    noStoresYet: 'لا توجد متاجر لهذا الحساب بعد.',
    createFirstStore: 'أنشئ متجرك الأول',

    // ---- Dashboard (stores list) ----
    instancesTitle: 'أدِر متاجرك',
    instancesSubtitle: 'كل متجر له محرك توصيات خاص. أنشئ، افحص، انسخ كود التوصيل، أو احذف متجرًا من هنا.',
    signInInstances: 'سجّل الدخول لرؤية متاجرك.',
    loadingInstances: 'جارٍ تحميل متاجرك...',
    totalInstancesLabel: 'إجمالي المتاجر',
    instanceNameLabel: 'اسم المتجر',
    instanceIdLabel: 'معرّف المتجر',
    createdDateLabel: 'تاريخ الإنشاء',
    apiKeyLabel: 'مفتاح API',
    usageLabel: 'الاستخدام',
    usageSuffix: 'حدث هذا الشهر',
    revealKey: 'إظهار مفتاح API',
    hideKey: 'إخفاء مفتاح API',
    getIntegrationCode: 'احصل على كود التوصيل',
    viewDashboard: 'عرض لوحة التحكم',
    deleteLabel: 'حذف',
    noInstancesYet: 'لا توجد متاجر بعد. أنشئ أول متجر للحصول على كود التوصيل ولوحة تحكم مباشرة.',
    deleteConfirm: 'حذف هذا المتجر؟ لا يمكن التراجع.',
    deleteFailed: 'تعذّر حذف هذا المتجر.',

    // ---- Dashboard (store detail) ----
    backToInstances: 'العودة للمتاجر',
    instanceDashboardEyebrow: 'لوحة المتجر',
    instanceDashSubtitle: 'مقاييس مباشرة من محرك التوصيات لهذا المتجر.',
    loadingInstanceDash: 'جارٍ تحميل لوحة المتجر...',
    systemHealthEyebrow: 'حالة النظام',
    liveEngineStatus: 'حالة المحرك المباشرة',
    mUptime: 'وقت التشغيل',
    mLatency: 'متوسط زمن الاستجابة',
    mErrorRate: 'معدل الأخطاء',
    mQueued: 'أحداث في الانتظار',
    mHealth: 'الصحة',
    engineUnreachableNote: 'محرك التوصيات غير متاح حاليًا. ستظهر المقاييس بمجرد اتصاله ومعالجته للأحداث.',
    instanceSettingsEyebrow: 'إعدادات المتجر',
    apiKeyIntegration: 'مفتاح API والتوصيل',
    showLabel: 'إظهار',
    hideLabelShort: 'إخفاء',
    copyIntegration: 'انسخ كود التوصيل',
    regenerateKey: 'إعادة توليد المفتاح',
    regenerateNote: 'يجب تأكيد إعادة توليد مفتاح API عبر عملية تدوير في الخادم قبل الاستخدام في الإنتاج.',
    pasteHeaderNote: 'انسخ هذا الكود وألصقه في رأس موقعك، أو استخدم خيار الإضافة في صفحة التوصيل.',
    topProductsEyebrow: 'أكثر المنتجات توصية',
    mostSuggested: 'ما يُقترح أكثر',
    colProduct: 'المنتج',
    colRank: 'الترتيب',
    colScore: 'النتيجة',
    noTrendingYet: 'لا توجد منتجات رائجة بعد. بمجرد أن يرسل متجرك أحداثًا، ستظهر المنتجات الشائعة هنا.',

    // ---- Dashboard (create store) ----
    superSimple: 'إعداد بسيط جدًا',
    createInstanceSubtitle: 'أنشئ متجرًا، ثم انسخ مفتاح API وكود التوصيل بعدها مباشرة.',
    signInCreate: 'سجّل الدخول قبل إنشاء متجر.',
    instanceCreated: 'تم إنشاء المتجر',
    copyKeyOnce: 'انسخ مفتاح API الآن. يُعرض مرة واحدة فقط.',
    integrationCodeLabel: 'كود التوصيل',
    copyLabel: 'نسخ',
    copiedLabel: 'تم النسخ',
    viewInstanceDash: 'عرض لوحة المتجر',
    integrationPageLabel: 'صفحة التوصيل',
    nextSteps: 'الخطوات التالية',
    newStep1: 'ألصق الكود في رأس متجرك.',
    newStep2: 'افتح لوحة المتجر لمتابعة الصحة والأداء.',
    newStep3: 'استخدم صفحة الدعم إذا احتجت مساعدة.',
    websiteUrlLabel: 'رابط الموقع',
    descriptionLabel: 'الوصف',
    cancelLabel: 'إلغاء',
    creatingLabel: 'جارٍ الإنشاء...',
    createInstanceBtn: 'إنشاء المتجر',
    createFailed: 'تعذّر إنشاء المتجر. حاول مرة أخرى.',
    phStoreName: 'متجر الأزياء الخاص بي',
    phStoreDesc: 'متجر ملابس نسائية',

    // ---- Dashboard (integration) ----
    integrationEyebrow: 'التوصيل',
    connectStoreTitle: 'اربط متجرك',
    integrationSubtitle: 'ثلاث خطوات لتشغيل التوصيات في الإنتاج.',
    signInIntegration: 'سجّل الدخول لرؤية تعليمات التوصيل.',
    createFirstIntegration: 'أنشئ متجرك الأول قبل تثبيت التوصيل.',
    pickInstance: 'اختر متجرًا',
    apiKeyAndSnippet: 'مفتاح API والكود',
    intStep1: 'انسخ مفتاح API',
    intStep2: 'أضف هذا الكود إلى موقعك',
    runLabel: 'تشغيل',
    downloadLabel: 'تنزيل',
    youreDone: 'انتهيت',
    recsWithin24: 'ستبدأ التوصيات بالظهور خلال 24 ساعة.',
    integrationReady: 'التوصيل جاهز',
    supportedPlatforms: 'المنصات المدعومة',
    chooseStack: 'اختر منصتك',
    platShopifyDesc: 'تثبيت التطبيق',
    platWooDesc: 'تنزيل الإضافة',
    platCustom: 'موقع مخصص',
    platCustomDesc: 'انسخ الكود',
    platMagentoDesc: 'قريبًا',
    runNote: 'ألصق الكود في رأس موقعك وأعد تحميل الصفحة لتفعيله.',

    // ---- Dashboard (settings) ----
    settingsEyebrow: 'الإعدادات',
    accountPreferences: 'الحساب والتفضيلات',
    settingsSubtitle: 'حدّث ملفك الشخصي والإشعارات وإعدادات الفوترة.',
    saveChanges: 'حفظ التغييرات',
    profileInfo: 'معلومات الملف الشخصي',
    accountDetails: 'تفاصيل الحساب',
    nameLabel: 'الاسم',
    companyLabel: 'اسم الشركة',
    settingsSaved: 'تم حفظ الإعدادات محليًا.',
    billingLabel: 'الفوترة',
    planUsage: 'الخطة والاستخدام',
    currentPlan: 'الخطة الحالية',
    usageNote: 'يُتابَع الاستخدام لكل متجر في لوحة كل متجر.',
    upgradePlan: 'ترقية الخطة',
    notificationsLabel: 'الإشعارات',
    alertsReports: 'التنبيهات والتقارير',
    emailNotifications: 'إشعارات البريد الإلكتروني',
    weeklyReport: 'تقرير أسبوعي',
    dangerZone: 'منطقة الخطر',
    deleteAccountTitle: 'حذف الحساب',
    deleteAccountNote: 'هذا الإجراء يتطلب تأكيدًا ويحذف بيانات حسابك نهائيًا.',
    deleteAccountBtn: 'حذف الحساب',

    // ---- Dashboard (support) ----
    supportEyebrow: 'الدعم',
    helpDocs: 'المساعدة والتوثيق',
    supportSubtitle: 'استخدم الأسئلة الشائعة أو الدليل أو نموذج التواصل أو صفحة الحالة عند الحاجة.',
    faqEyebrow: 'الأسئلة الشائعة',
    commonQuestions: 'أسئلة متكررة',
    faqQ1: 'كم من الوقت حتى تظهر التوصيات؟',
    faqA1: 'عادة خلال 24 ساعة بعد تثبيت كود التوصيل وبدء حركة الزوار.',
    faqQ2: 'هل أستخدم حسابًا واحدًا لعدة متاجر؟',
    faqA2: 'نعم. يجب أن يستخدم كل متجر نسخته الخاصة حتى تبقى التحليلات والمفاتيح منفصلة.',
    faqQ3: 'ماذا لو احتجت مساعدة في الإعداد؟',
    faqA3: 'استخدم نموذج التواصل أدناه أو افتح التوثيق للإرشادات وحل المشكلات.',
    linksEyebrow: 'روابط',
    quickResources: 'موارد سريعة',
    documentationLabel: 'التوثيق',
    contactSupport: 'تواصل مع الدعم',
    statusPageLabel: 'صفحة الحالة',
    sendMessage: 'أرسل رسالة',
    messageLabel: 'الرسالة',
    phMessage: 'أخبرنا بما تحتاج المساعدة فيه',

    // ---- Dashboard (sidebar) ----
    navDashboard: 'لوحة التحكم',
    navInstances: 'المتاجر',
    navIntegration: 'التوصيل',
    navSettings: 'الإعدادات',
    navSupport: 'الدعم',
    sidebarCreate: 'إنشاء متجر',
    backToSite: 'العودة للموقع',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('EN');

  // Restore the saved language on mount.
  useEffect(() => {
    const saved = localStorage.getItem('language');
    if (saved === 'EN' || saved === 'FR' || saved === 'AR') {
      setLanguageState(saved);
    }
  }, []);

  // Persist the choice and keep document direction/lang in sync (RTL for Arabic).
  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.setAttribute('lang', language.toLowerCase());
    document.documentElement.setAttribute('dir', language === 'AR' ? 'rtl' : 'ltr');
  }, [language]);

  const setLanguage = (lang: Language) => setLanguageState(lang);

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['EN']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      <div dir={language === 'AR' ? 'rtl' : 'ltr'}>
        {children}
      </div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
